### ISSUE TITLE
python3-unidecode required

### ISSUE THREAD

**Issue by tuxick** [dlenski/lexeme#4]
Tried to run lexeme gave me:
`AttributeError: 'Namespace' object has no attribute 'strip_diacritics'`

Installing python3-unidecode fixed that. Additional check required, or update in Readme?

**Comment by dlenski** [comment]
Good catch. 

> Additional check required, or update in Readme?

It was meant to be an optional dependency, not a required one :man_facepalming: 

Should be fixed, so that `lexeme` will continue to run (albeit without the `--strip-diacritics` option) if `unidecode` isn't installed.
